
let url = {
  role_type:0,
  user:{
    Login:'common/role/Account/Login',
    Logout:'common/role/Account/Logout',
    ForgetPassword:'common/role/Account/ForgetPassword',
    GetPublicCode:'common/role/verificationCode/GetPublicCode',//账户未登录时发送验证码接口
    GetLoginCode:'common/role/VerificationCode/GetLoginCode',//账户登录后发送验证码接口
    ChangePasswordByOld:'common/role/Account/ChangePasswordByOld',//后台端根据旧密码修改密码接口
    GetInfo:'common/role/Account/GetInfo',//后台端获取账户信息接口
    ChangeInfo:'common/role/Account/ChangeInfo',//后台端修改账户信息接口
    ChangeMobile:'common/role/Account/ChangeMobile',//后台端修改手机号接口
    ChangePasswordByCode:'common/role/Account/ChangePasswordByCode',//后台端根据验证码修改密码接口
    GetValidList:'common/Area/GetValidList',//获取地址列表信息接口
    GetMultilevelList:'common/Area/GetMultilevelList',//根据当前的area_ids获取多级地址列表信息接口，仅显示有效的
  },
  control:{
    AddAres:'control/setting/Area/Add',//总平台管理端新增地址信息接口
    ChangeStatusByIds:'control/setting/Area/ChangeStatusByIds',//总平台管理端批量修改地址可用状态接口
    DelAreaByIds:'control/setting/Area/DelByIds',//总平台管理端批量删除地址接口
    EditAreaById:'control/setting/Area/EditById',//总平台管理端修改地址信息接口
    GetAreaInfoById:'control/setting/Area/GetInfoById',//总平台管理端获取地址详情信息接口
    GetAreaList:'control/setting/Area/GetList',//总平台管理端获取地址列表信息接口[非总后台请勿调用该接口]
    UpdateAreaData:'control/setting/Area/UpdateAreaData',//总平台管理端更新区域数据
    UpdateDisplayOrderById:'control/setting/Area/UpdateDisplayOrderById',//总平台管理端修改地址排序接口
    SmsGetConfig:'control/setting/Sms/GetConfig',//总平台管理端获取短信接口设置信息接口
    SmsSaveConfig:'control/setting/Sms/SaveConfig',//总平台管理端修改短信接口设置信息接口
    GetCommonCategoryList:'control/setting/CommonCategory/GetList',//总平台管理端获取通用分类列表信息接口[非总后台请勿调用该接口]
    DelCommonCategoryByIds:'control/setting/CommonCategory/DelByIds',//总平台管理端批量删除通用分类接口
    AddCommonCategory:'control/setting/CommonCategory/Add',//总平台管理端新增通用分类信息接口
    EditCommonCategoryById:'control/setting/CommonCategory/EditById',//总平台管理端修改通用分类信息接口
    UpdateCommonCategoryDisplayOrderByIds:'control/setting/CommonCategory/UpdateDisplayOrderByIds',//总平台管理端统一修改所有通用分类排序接口
    
    GetDiyListPage:'control/temp/DiyPage/GetListPage',//control/temp/DiyPage/GetListPage
    GetDiyPageMenu:'control/temp/DiyPage/GetMenu',//获取后台菜单栏目信息
    GetNavbarList:'cloud/diyPage/Navbar/GetList',//获取指定角色类型对应的侧边栏目信息
  },
  File:{
    AddImage:'basic/upload/File/AddImage',//后台账户上传图片通用接口
    AddImageByUrl:'basic/upload/File/AddImageByUrl',//后台账户上传图片通用接口
  },
  Group:{
    GetList:'common/attachment/Group/GetList',//获取本地附件空间类型对应的分组列表
    Add:'common/attachment/Group/Add',//新增一个远程附件分组
    DelInfoById:'common/attachment/Group/DelInfoById',//根据附件分组ID删除远程附件分组信息
    ChangeInfoById:'common/attachment/Group/ChangeInfoById',//根据附件分组ID修改远程附件分组信息
    GetPtGroupList:'cloud/common/attachment/Group/GetList',//获取平台可用的附件空间类型对应的分组列表

  },
  attachmentLog:{
    GetList:'common/attachment/Log/GetList',//获取附件空间类型对应的配置列表
    cloudGetList:'cloud/common/attachment/Log/GetList',//获取平台附件空间类型对应的配置列表
    ChangeBdGroupByIds:'common/attachment/Log/ChangeGroupByIds',//批量修改本地图片所属分组
  
  },


  common:{
    GetRoleType:'cloud/common/Code/GetRoleType',//获取角色类型码接口
  },
  PermGroup:{//总后台角色组
    GetList:'main/operate/PermGroup/GetList',//获取通用角色组列表信息接口
    Statistics:'main/operate/PermGroup/Statistics',//角色组信息接口
    AddPermGroup:'main/operate/PermGroup/Add',//新增角色组信息接口
    ChangeStatusByIds:'main/operate/PermGroup/ChangeStatusByIds',//批量修改角色组可用状态接口
    DelByIds:'main/operate/PermGroup/DelByIds',//批量删除角色组信息接口
    GetInfoById:'main/operate/PermGroup/GetInfoById',//获取角色组详情信息接口
    EditById:'main/operate/PermGroup/EditById',//修改角色组信息接口
  },
  commonPermGroup:{//通用角色组
    GetList:'common/role/PermGroup/GetList',//获取通用角色组列表信息接口
    ChangeStatusByIds:'common/role/PermGroup/ChangeStatusByIds',//批量修改角色组可用状态接口
    Add:'common/role/PermGroup/Add',//新增角色组信息接口
    GetInfoById:'common/role/PermGroup/GetInfoById',//获取角色组详情信息接口
    DelByIds:'common/role/PermGroup/DelByIds',//批量删除角色组信息接口
    EditById:'common/role/PermGroup/EditById',//修改角色组信息接口
  },
  PermAccount:{//操作员
    GetAllGroupList:'common/role/PermAccount/GetAllGroupList',
    GetList:'common/role/PermAccount/GetList',//获取账户列表信息接口
    ChangeStatusById:'common/role/PermAccount/ChangeStatusById',//修改账号状态
    DeleteByIds:'common/role/PermAccount/DeleteByIds',//批量删除账号信息
    Add:'common/role/PermAccount/Add',//新增账户信息接口
    GetInfoById:'common/role/PermAccount/GetInfoById',//获取账户信息接口
    ChangeInfoById:'common/role/PermAccount/ChangeInfoById',//后台端修改账户信息接口
    GetAllInfoById:'common/role/PermAccount/GetAllInfoById',//获取操作员全部资料信息接口
    GetOperationLogList:'common/role/OperationLog/GetList',//获取日志列表信息接口
    GetCategoryAllList:'common/common/Category/GetAllList',//一次性获取所有的分类列表信息接口
    GetAllInterestList:'common/common/Interest/GetAllList',//一次性获取所有的兴趣爱好列表信息接口
    GetAllAccountList:'common/role/PermAccount/GetAllAccountList',//获取所有的操作员列表接口
    GetAllLogTypeList:'common/role/OperationLog/GetAllLogTypeList',//获取所有日志类型列表接口
    ChangeAllInfoById:'common/role/PermAccount/ChangeAllInfoById',//修改账户全部资料信息接口
  },
  Category:{
    GetAllList:'main/common/Category/GetAllList',//一次性获取所有的分类列表信息接口
    ChangeStatusByIds:'main/common/Category/ChangeStatusByIds',//批量修改分类可用状态接口
    UpdateMenuDisplayOrder:'main/common/Category/UpdateMenuDisplayOrder',//更新分类排序信息接口
    DelByIds:'main/common/Category/DelByIds',//批量删除分类信息接口
    Add:'main/common/Category/Add',//新增分类信息接口
    EditById:'main/common/Category/EditById',//修改分类信息接口
    GetInfoById:'main/common/Category/GetInfoById',//获取分类的详情信息接口
    GetSubList:'main/common/Category/GetSubList',//获取所有下级分类列表信息接口
    
  },
  Interest:{
    GetAllList:'main/common/Interest/GetAllList',//一次性获取所有的兴趣爱好列表信息接口
    Add:'main/common/Interest/Add',//新增兴趣爱好信息接口
    EditById:'main/common/Interest/EditById',//修改兴趣爱好信息接口
    DelByIds:'main/common/Interest/DelByIds',//批量删除兴趣爱好信息接口

  },
  Bank:{
    GetList:'main/operate/Bank/GetList',//获取合作银行列表
    Add:'main/operate/Bank/Add',//新增合作银行
    DeleteBankByIds:'main/operate/Bank/DeleteBankByIds',//批量删除文件日志信息
    GetInfoById:'main/operate/Bank/GetInfoById',//获取合作银行详细信息
    ChangeInfoById:'main/operate/Bank/ChangeInfoById',//修改合作银行信息

  },
  QQAuth:{
    GetInfo:'main/common/setting/QQAuth/GetInfo',//获取QQ授权信息接口
    SaveInfo:'main/common/setting/QQAuth/SaveInfo',//修改QQ授权信息接口
    ChangeStatus:'main/common/setting/QQAuth/ChangeStatus',//修改QQ授权状态接口
  },
  WeChatAuth:{
    GetInfo:'main/common/setting/WeChatAuth/GetInfo',//获取微信授权信息接口
    SaveInfo:'main/common/setting/WeChatAuth/SaveInfo',//修改微信授权信息接口
    ChangeStatus:'main/common/setting/WeChatAuth/ChangeStatus',//修改微信授权状态接口
  },
  Mailer:{
    GetInfo:'main/common/setting/Mailer/GetInfo',//获取邮箱服务信息接口
    SaveInfo:'main/common/setting/Mailer/SaveInfo',//修改邮箱服务信息接口
    SendTestMailer:'main/common/setting/Mailer/SendTestMailer',//使用当前配置的邮箱服务器发送测试邮件接口
  },
  SensitiveWord:{
    GetList:'main/common/SensitiveWord/GetList',//获取敏感词列表信息接口
    Add:'main/common/SensitiveWord/Add',//新增敏感词信息接口
    EditById:'main/common/SensitiveWord/EditById',//修改敏感词信息接口
    DelByIds:'main/common/SensitiveWord/DelByIds',//批量删除敏感词信息接口
    EditById:'main/common/SensitiveWord/EditById',//修改敏感词信息接口
    Export:'main/common/SensitiveWord/Export',//根据搜索条件导出查询出来的敏感词文件
    Import:'main/common/SensitiveWord/Import',//导入敏感词文件，已存在的敏感词自动过滤
    ImportTemp:'main/common/SensitiveWord/ImportTemp',//下载导出敏感词模板文件
  },
  Protocol:{
    GetList:'main/common/Protocol/GetList',//获取协议列表信息接口
    ChangeStatusByIds:'main/common/Protocol/ChangeStatusByIds',
    GetInfoById:'main/common/Protocol/GetInfoById',//获取协议列表信息接口
    ChangeInfoById:'main/common/Protocol/ChangeInfoById',//修改协议信息接口
  },
  Account:{
    BindEmail:'common/role/Account/BindEmail',//后台端绑定邮箱接口
    ChangeEmail:'common/role/Account/ChangeEmail',//后台端修改邮箱接口
    GetLoginCode:'common/role/EmailCode/GetLoginCode',//在已经登录账号的情况获取邮箱验证码
    GetBindInfo:'common/role/Account/GetBindInfo',//获取账户安全绑定信息接口
    UnbindEmail:'common/role/Account/UnbindEmail',//后台端解绑邮箱接口
    ChangeEmergencyInfo:'common/role/Account/ChangeEmergencyInfo',//修改紧急联系人信息
    DelEmergencyInfo:'common/role/Account/DelEmergencyInfo',//删除紧急联系人信息
  },
  Area:{
    GetSubList:'main/common/Area/GetSubList',//获取所有下级区域列表信息接口
    ChangeStatusByIds:'main/common/Area/ChangeStatusByIds',//批量修改区域可用状态接口
    Add:'main/common/Area/Add',//新增区域信息接口
    EditById:'main/common/Area/EditById',//修改区域信息接口
    GetInfoById:'main/common/Area/GetInfoById',//获取区域的详情信息接口
    DelByIds:'main/common/Area/DelByIds',//批量删除区域信息接口
    GetWeChatAuthUrlBindAccount:'cloud/setting/WeChatAuth/GetWeChatAuthUrlBindAccount',//获取后台绑定微信的授权链接接口
    UnbindWeChat:'common/role/Account/UnbindWeChat',//后台端解绑邮箱接口
    CheckBindWeChat:'common/role/Account/CheckBindWeChat',//后台端个人中心检查账号是否绑定微信接口

  },

  cloud:{
    Perm:{
      GetPermByRoleType:'cloud/role/Perm/GetPermByRoleType',//获取角色类型所有权限列表
    },
    Bank:{
      GetList:'cloud/finance/Bank/GetList',
    },
    WeChat:{
      GetLoginAccountUrl:'cloud/auth/WeChat/GetLoginAccountUrl',//获取PC后台微信扫码登录授权链接接口
      CheckAccountLogin:'cloud/auth/WeChat/CheckAccountLogin',//微信登录后台 -- 循环请求是否微信登录成功 ， 成功则返回账号登录信息
      
    }
  }
}

export default url